### PR TITLE
Add support for Visual Studio 2022

### PR DESCRIPTION
**Pull request by shoaibshakeel381**
This PR refactored full project according to Microsofts documentation to support both older x86 and newer x64 architecture based Visual Studio editions.

### CODE REVIEW

**Comment by nbelyh** [comment]
@shoaibshakeel381 
Thank you for the fix! Sorry for the late response - on vacations now.
Question - why changing extension id?

**Comment by shoaibshakeel381** [comment]
I thought you might have stopped working on this project, so I just changed extension id and published extension to market place. Reverted change

**Comment by nbelyh** [comment]
I'll check against the older versions of VS and merge over the weekend 👍

**Comment by ahmed-ghoniem** [comment]
Hello @nbelyh 
When you have time could you please check this PR to support Visual studio 2022? 
Thanks in advance

**Comment by nbelyh** [comment]
Hi @ahmed-ghoniem. Unfortunately this PR breaks the compatibility with previous versions of Visual Studio (means, if I merge it, the extension will stoped working in other versions of VS for some reason). Therefore I avoid merging it for now, not sure about the timeframe, will go for a simpler config modification probably.

**Pull request closed without merging**
